-- 00_schemas.sql
CREATE SCHEMA IF NOT EXISTS util;
CREATE SCHEMA IF NOT EXISTS settings;
CREATE SCHEMA IF NOT EXISTS market;
CREATE SCHEMA IF NOT EXISTS docs;
CREATE SCHEMA IF NOT EXISTS wallet;
CREATE SCHEMA IF NOT EXISTS matrices;
CREATE SCHEMA IF NOT EXISTS str_aux;
CREATE SCHEMA IF NOT EXISTS cin_aux;
CREATE SCHEMA IF NOT EXISTS ingest;
CREATE SCHEMA IF NOT EXISTS strategy_aux;
CREATE SCHEMA IF NOT EXISTS mea;
CREATE SCHEMA IF NOT EXISTS mea_dynamics;
CREATE SCHEMA IF NOT EXISTS ops;
CREATE SCHEMA IF NOT EXISTS ext;

-- Optional: version marker
COMMENT ON SCHEMA util IS 'Utility helpers (triggers/functions)';
